config/routes.rb
Uts::Application.routes.draw do
  resources :journal_authors

  resources :chapter_authors

  resources :book_authors

  resources :books

  resources :chapters

  resources :journals

  resources :websites

  resources :authors

  get "pages/about"
  get "pages/contact"
  get "pages/home"

  root 'pages#home'

end

app/models/chapter_author.rb
class ChapterAuthor < ActiveRecord::Base
	belongs_to :chapter
end

app/controllers/chapter_authors_controller.rb
class ChapterAuthorsController < ApplicationController
  before_action :set_chapter_author, only: [:show, :edit, :update, :destroy]

  # GET /chapter_authors
  # GET /chapter_authors.json
  def index
    @chapter_authors = ChapterAuthor.all
  end

  # GET /chapter_authors/1
  # GET /chapter_authors/1.json
  def show
  end

  # GET /chapter_authors/new
  def new
    @chapter_author = ChapterAuthor.new
  end

  # GET /chapter_authors/1/edit
  def edit
  end

  # POST /chapter_authors
  # POST /chapter_authors.json
  def create
    @chapter_author = ChapterAuthor.new(chapter_author_params)

    respond_to do |format|
      if @chapter_author.save
        format.html { redirect_to @chapter_author, notice: 'Chapter author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter_author }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter_authors/1
  # PATCH/PUT /chapter_authors/1.json
  def update
    respond_to do |format|
      if @chapter_author.update(chapter_author_params)
        format.html { redirect_to @chapter_author, notice: 'Chapter author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapter_authors/1
  # DELETE /chapter_authors/1.json
  def destroy
    @chapter_author.destroy
    respond_to do |format|
      format.html { redirect_to chapter_authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter_author
      @chapter_author = ChapterAuthor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_author_params
      params.require(:chapter_author).permit(:chapter_id, :first_name, :last_name)
    end
end

app/helpers/chapter_authors_helper.rb
module ChapterAuthorsHelper
end

app/views/chapter_authors/_form.html.haml
= form_for @chapter_author do |f|
  - if @chapter_author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chapter_author.errors.count, "error")} prohibited this chapter_author from being saved:"
      %ul
        - @chapter_author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :chapter_id
    = f.number_field :chapter_id
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .actions
    = f.submit 'Save'

app/views/chapter_authors/edit.html.haml
%h1 Editing chapter_author

= render 'form'

= link_to 'Show', @chapter_author
\|
= link_to 'Back', chapter_authors_path

app/views/chapter_authors/index.html.haml
%h1 Listing chapter_authors

%table
  %tr
    %th Chapter
    %th First name
    %th Last name
    %th
    %th
    %th

  - @chapter_authors.each do |chapter_author|
    %tr
      %td= chapter_author.chapter_id
      %td= chapter_author.first_name
      %td= chapter_author.last_name
      %td= link_to 'Show', chapter_author
      %td= link_to 'Edit', edit_chapter_author_path(chapter_author)
      %td= link_to 'Destroy', chapter_author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Chapter author', new_chapter_author_path

app/views/chapter_authors/new.html.haml
%h1 New chapter_author

= render 'form'

= link_to 'Back', chapter_authors_path

app/views/chapter_authors/show.html.haml
%p#notice= notice

%p
  %b Chapter:
  = @chapter_author.chapter_id
%p
  %b First name:
  = @chapter_author.first_name
%p
  %b Last name:
  = @chapter_author.last_name

= link_to 'Edit', edit_chapter_author_path(@chapter_author)
\|
= link_to 'Back', chapter_authors_path