config/routes.rb
Uts::Application.routes.draw do
  resources :journal_authors

  resources :chapter_authors

  resources :book_authors

  resources :books

  resources :chapters

  resources :journals

  resources :websites

  resources :authors

  get "pages/about"
  get "pages/contact"
  get "pages/home"

  root 'pages#home'

end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
	belongs_to :book
end

app/controllers/book_authors_controller.rb
class BookAuthorsController < ApplicationController
  before_action :set_book_author, only: [:show, :edit, :update, :destroy]

  # GET /book_authors
  # GET /book_authors.json
  def index
    @book_authors = BookAuthor.all
  end

  # GET /book_authors/1
  # GET /book_authors/1.json
  def show
  end

  # GET /book_authors/new
  def new
    @book_author = BookAuthor.new
  end

  # GET /book_authors/1/edit
  def edit
  end

  # POST /book_authors
  # POST /book_authors.json
  def create
    @book_author = BookAuthor.new(book_author_params)

    respond_to do |format|
      if @book_author.save
        format.html { redirect_to @book_author, notice: 'Book author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book_author }
      else
        format.html { render action: 'new' }
        format.json { render json: @book_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_authors/1
  # PATCH/PUT /book_authors/1.json
  def update
    respond_to do |format|
      if @book_author.update(book_author_params)
        format.html { redirect_to @book_author, notice: 'Book author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_authors/1
  # DELETE /book_authors/1.json
  def destroy
    @book_author.destroy
    respond_to do |format|
      format.html { redirect_to book_authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_author
      @book_author = BookAuthor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_author_params
      params.require(:book_author).permit(:book_id, :first_name, :last_name)
    end
end

app/helpers/book_authors_helper.rb
module BookAuthorsHelper
end

app/views/book_authors/_form.html.haml
= form_for @book_author do |f|
  - if @book_author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book_author.errors.count, "error")} prohibited this book_author from being saved:"
      %ul
        - @book_author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :book_id
    = f.number_field :book_id
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .actions
    = f.submit 'Save'

app/views/book_authors/edit.html.haml
%h1 Editing book_author

= render 'form'

= link_to 'Show', @book_author
\|
= link_to 'Back', book_authors_path

app/views/book_authors/index.html.haml
%h1 Listing book_authors

%table
  %tr
    %th Book
    %th First name
    %th Last name
    %th
    %th
    %th

  - @book_authors.each do |book_author|
    %tr
      %td= book_author.book_id
      %td= book_author.first_name
      %td= book_author.last_name
      %td= link_to 'Show', book_author
      %td= link_to 'Edit', edit_book_author_path(book_author)
      %td= link_to 'Destroy', book_author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Book author', new_book_author_path

app/views/book_authors/new.html.haml
%h1 New book_author

= render 'form'

= link_to 'Back', book_authors_path

app/views/book_authors/show.html.haml
%p#notice= notice

%p
  %b Book:
  = @book_author.book_id
%p
  %b First name:
  = @book_author.first_name
%p
  %b Last name:
  = @book_author.last_name

= link_to 'Edit', edit_book_author_path(@book_author)
\|
= link_to 'Back', book_authors_path