config/routes.rb
Uts::Application.routes.draw do
  resources :journal_authors

  resources :chapter_authors

  resources :book_authors

  resources :books

  resources :chapters

  resources :journals

  resources :websites

  resources :authors

  get "pages/about"
  get "pages/contact"
  get "pages/home"

  root 'pages#home'

end

app/models/journal.rb
class Journal < ActiveRecord::Base
	has_many :journal_authors
	accepts_nested_attributes_for :journal_authors
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    author_count = @journal.journal_authors.count
    author_map = @journal.journal_authors.each_with_index.map{|a, i|
      if i == 0
        if a.first_name.blank?
          "#{a.last_name}"
        else
          "#{a.last_name}, #{a.first_name.strip.first}."
        end
      elsif i < author_count -1
        if a.first_name.blank?
          ", #{a.last_name}"
        else
          ", #{a.last_name}, #{a.first_name.strip.first}."
        end
      else
        if a.first_name.blank?
          "&nbsp;& #{a.last_name},"
        else
          "&nbsp;& #{a.last_name}, #{a.first_name.strip.first}. "
        end
      end
    }.compact
    @author_string = author_map.join("")
    top = @journal.page_range_end
    vol = "&nbsp;vol. #{@journal.journal_volume}," unless @journal.journal_volume.blank?
    jo = "&nbsp;no. #{@journal.journal_number}," unless @journal.journal_volume.blank?
    #@first = "#{@author_string} #{@journal.publication_year.strftime('%Y')}, '#{@journal.article_title}',"
    #@ital = "#{@journal.journal_title},"
    #@rest = "vol. #{@journal.journal_volume}, no. #{@journal.journal_number}, pp. #{@journal.page_range_start}-#{top}."
    @ref = "#{@author_string} #{@journal.publication_year.strftime('%Y')}, '#{@journal.article_title}', <i>#{@journal.journal_title}</i>,#{vol}#{jo} pp. #{@journal.page_range_start}-#{top}."
  end

  # GET /journals/new
  def new
    @journal = Journal.new
    @journal.journal_authors.build
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal }
        format.json { render action: 'show', status: :created, location: @journal }
      else
        format.html { render action: 'new' }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:publication_year, :article_title, :journal_title, :journal_volume, :journal_number, :page_range_start, :page_range_end, journal_authors_attributes: [:id, :first_name, :_destroy, :last_name, :journal_id])
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.haml
.ref-form-area
  .ref-form
    = nested_form_for @journal do |f|
      - if @journal.errors.any?
        #error_explanation
          %h2= "#{pluralize(@journal.errors.count, "error")} prohibited this journal from being saved:"
          %ul
            - @journal.errors.full_messages.each do |msg|
              %li= msg
      =f.fields_for :journal_authors do |t|
        .field
          =t.text_field :first_name, placeholder: "Author First Name or Initial"
        
        .field
          =t.text_field :last_name, placeholder: "Author Last Name or Initial"
        .hide.remove-author=t.link_to_remove "Remove Author >>"
      %p
        =f.link_to_add "Add another Author >>", :journal_authors, class: "add-author"
      .field
        .extra-label.pull-left
          Journal Publication Year:
        .pull-right
          = f.datetime_select :publication_year, discard_month: true, discard_hour:true, start_year: Time.now.year - 300, end_year: Time.now.year
          = f.label " "
        .clearfix
      .field
        = f.text_field :article_title, placeholder: "Article Title"
      .field
        = f.text_field :journal_title, placeholder: "Journal Title"
      .field
        = f.text_field :journal_volume, placeholder: "Volume Number (just the number)" 
      .field
        = f.text_field :journal_number, placeholder: "Journal Number (just the number)" 
      .field
        = f.text_field :page_range_start, placeholder: "Page Start Range (i.e. 145)"
      .field
        = f.text_field :page_range_end, placeholder: "Page End Range (i.e. 280)"
      .actions
        .pomegranate-flat-button
          = f.submit 'Create Reference'

app/views/journals/edit.html.haml
%h1 Editing journal

= render 'form'

= link_to 'Show', @journal
\|
= link_to 'Back', journals_path

app/views/journals/index.html.haml
%h1 Listing journals

%table
  %tr
    %th Publication year
    %th Article title
    %th Journal title
    %th Journal volume
    %th Journal number
    %th Page range start
    %th Page range end
    %th
    %th
    %th

  - @journals.each do |journal|
    %tr
      %td= journal.publication_year
      %td= journal.article_title
      %td= journal.journal_title
      %td= journal.journal_volume
      %td= journal.journal_number
      %td= journal.page_range_start
      %td= journal.page_range_end
      %td= link_to 'Show', journal
      %td= link_to 'Edit', edit_journal_path(journal)
      %td= link_to 'Destroy', journal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Journal', new_journal_path

app/views/journals/new.html.haml
%h1 Create a Journal Reference

= render 'form'

app/views/journals/show.html.haml
%h1 Your Journal Reference
.ref-form-area
  .ref-form
    #fe_text{:cols => "100", :rows => "3"}
      =@ref.html_safe
    %button#d_clip_button.my_clip_button{"data-clipboard-target" => "fe_text", "data-clipboard-text" => "Default clipboard text from attribute", :title => "Click me to copy to clipboard."}
      %b Click to Copy to Clipboard...
.text-center
  = link_to 'Edit This Reference', edit_journal_path(@journal)
  \|
  = link_to 'Back to Home', root_path

:javascript
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });