config/routes.rb
Uts::Application.routes.draw do
  resources :journal_authors

  resources :chapter_authors

  resources :book_authors

  resources :books

  resources :chapters

  resources :journals

  resources :websites

  resources :authors

  get "pages/about"
  get "pages/contact"
  get "pages/home"

  root 'pages#home'

end

app/models/author.rb
class Author < ActiveRecord::Base
	belongs_to :book
	belongs_to :chapter
	belongs_to :journal
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :book_authors
	accepts_nested_attributes_for :book_authors
end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
	belongs_to :book
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_many :chapter_authors
	accepts_nested_attributes_for :chapter_authors
end

app/models/chapter_author.rb
class ChapterAuthor < ActiveRecord::Base
	belongs_to :chapter
end

app/models/journal.rb
class Journal < ActiveRecord::Base
	has_many :journal_authors
	accepts_nested_attributes_for :journal_authors
end

app/models/journal_author.rb
class JournalAuthor < ActiveRecord::Base
	belongs_to :journal
end

app/models/website.rb
class Website < ActiveRecord::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    #author_string
    author_count = @book.book_authors.count
    author_map = @book.book_authors.each_with_index.map{|a, i|
      if i < author_count -1
        if a.first_name.blank?
          "#{a.last_name} & "
        else
          "#{a.last_name}, #{a.first_name.strip.first}. & "
        end
      else
        if a.first_name.blank?
          "#{a.last_name}"
        else
          "#{a.last_name}, #{a.first_name.strip.first}."
        end
      end
    }.compact
    @author_string = author_map.join("")
    @be = "#{@book.book_edition},&nbsp;" unless @book.book_edition.blank?
    #@first = "#{@author_string} #{@book.publication_year.strftime('%Y')},"
    #@ital = @book.book_title#Applied solid mechanics
    #@rest = ", #{@book.book_edition}, #{@book.publisher_name}, #{@book.publisher_city}."
    @ref = "#{@author_string} #{@book.publication_year.strftime('%Y')}, <i>#{@book.book_title}</i>, #{@be}#{@book.publisher_name}, #{@book.publisher_city}."
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.book_authors.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book}
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:publication_year, :book_title, :book_edition, :publisher_name, :publisher_city,book_authors_attributes: [:id, :first_name, :_destroy, :last_name, :book_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_authors_helper.rb
module BookAuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapter_authors_helper.rb
module ChapterAuthorsHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56122023-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
	<ul class="nav">
		<%= link_to(root_path, :class => 'brand', style: 'max-width:25px;')  do %>
			<%= image_tag('school.png', style: "max-width: 90px;") %>
		<% end %>
		UTS Havard Reference Guide by
		<%=link_to "Ben Gruber", "http://www.bengruber.me" %>
		<li class="hide"><%= link_to 'About', pages_about_path %></li>
	</ul>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "UTS Havard Referencing"
    %meta{:content => content_for?(:description) ? yield(:description) : "UTS Havard Referencing", :name => "Havard Referencing"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = csrf_meta_tags
    = render "layouts/ga"
    = yield(:head)
  %body
    %header.navbar
      %nav.navbar-default{:role => "navigation"}
        .container-fluid
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
    %footer

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.haml
%h1 Choose Your Reference Type
.panel-reminder.text-center
	%p 
		This site allows you to easily create a Havard UTS reference for websites, books, book chapters, and journals. 
		%br
		The guidelines are taken from the UTS guidlines on the UTS site
		=link_to "here.", "https://www.lib.uts.edu.au/help/referencing/harvard-uts-referencing-guide"
		The site was last updated on October 27, 2014

.home-center.text-center
	=link_to new_website_path do
		.home-box.pull-left
			%h4 Website Reference
			=image_tag("website-white.png", style: "width: 100px;")
	.home-break.pull-left
		&nbsp;

	=link_to new_book_path do
		.home-box.pull-left
			%h4 Book Reference
			=image_tag("book-white.png", style: "width: 100px;")
		
	.home-break.pull-left
		&nbsp;

	=link_to new_chapter_path do
		.home-box.pull-left
			%h4 Book Chapter Reference
			=image_tag("chapter-white.png", style: "width:100px;")
		
	.home-break.pull-left
		&nbsp;

	=link_to new_journal_path do 
		.home-box.pull-left
			%h4 Journal Reference
			=image_tag("journal-white.png", style: "width: 100px;")
			
	.clearfix